DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
    ID INTEGER NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR (255) NOT NULL ,
    ENABLED BOOLEAN NOT NULL

);



DROP TABLE IF EXISTS AUTHORITIES;
CREATE TABLE AUTHORITIES(
    USERNAME VARCHAR(250) NOT NULL,
    AUTHORITY VARCHAR (250) NOT NULL

);


DROP TABLE IF EXISTS FOOD;
CREATE TABLE FOOD(
    ID  INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUCTCATEGORY  VARCHAR(250) NOT NULL,
    PRICE INTEGER NOT NULL,
    TITLE   VARCHAR(250) NOT NULL,
    DESCRIPTION  VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS DRINK;
CREATE TABLE DRINK(
    ID  INTEGER NOT NULL PRIMARY KEY  AUTO_INCREMENT,
    PRODUCTCATEGORY  VARCHAR(250) NOT NULL,
    PRICE INTEGER NOT NULL,
    TITLE   VARCHAR(250) NOT NULL,
    DESCRIPTION  VARCHAR(250) NOT NULL
);


