DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR (255) NOT NULL ,
    ENABLED BOOLEAN NOT NULL,
    AUTHORITY VARCHAR (250) NOT NULL
);



DROP TABLE IF EXISTS AUTHORITIES;
CREATE TABLE AUTHORITIES(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(250) NOT NULL,
    AUTHORITY VARCHAR (250) NOT NULL

);


DROP TABLE IF EXISTS FOOD;
CREATE TABLE FOOD(
    ID  INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION  VARCHAR(250) NOT NULL,
    PRICE INTEGER NOT NULL,
    PRODUCTCATEGORY  VARCHAR(250) NOT NULL,
    TITLE   VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS DRINK;
CREATE TABLE DRINK(
    ID  INTEGER NOT NULL PRIMARY KEY  AUTO_INCREMENT,
    DESCRIPTION  VARCHAR(250) NOT NULL,
    PRICE INTEGER NOT NULL,
    PRODUCTCATEGORY  VARCHAR(250) NOT NULL,
    TITLE   VARCHAR(250) NOT NULL
);



DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS(
    ID  INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUCTID  INTEGER NOT NULL,
    PRODUCTCOUNT INTEGER NOT NULL,
    TOTALPRICE  INTEGER NOT NULL,
    ORDERDATE   TIMESTAMP,
    PAYMENTTYPE VARCHAR(250) NOT NULL
);

