//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.03 at 09:29:17 PM EET 
//


package com.resturant.restapi.stub;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.resturant.restapi.stub package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CustomerCity_QNAME = new QName("http://model.ba.com/xsd", "city");
    private final static QName _CustomerFirstName_QNAME = new QName("http://model.ba.com/xsd", "firstName");
    private final static QName _CustomerLastName_QNAME = new QName("http://model.ba.com/xsd", "lastName");
    private final static QName _CustomerAddress_QNAME = new QName("http://model.ba.com/xsd", "address");
    private final static QName _CustomerPhoneNumber_QNAME = new QName("http://model.ba.com/xsd", "phoneNumber");
    private final static QName _GetCustomerCustomer_QNAME = new QName("http://service.ba.com", "customer");
    private final static QName _GetCustomerResponseReturn_QNAME = new QName("http://service.ba.com", "return");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.resturant.restapi.stub
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link AddCustomerResponse }
     * 
     */
    public AddCustomerResponse createAddCustomerResponse() {
        return new AddCustomerResponse();
    }

    /**
     * Create an instance of {@link GetAllCustomerResponse }
     * 
     */
    public GetAllCustomerResponse createGetAllCustomerResponse() {
        return new GetAllCustomerResponse();
    }

    /**
     * Create an instance of {@link GetCustomer }
     * 
     */
    public GetCustomer createGetCustomer() {
        return new GetCustomer();
    }

    /**
     * Create an instance of {@link UpdateCustomerResponse }
     * 
     */
    public UpdateCustomerResponse createUpdateCustomerResponse() {
        return new UpdateCustomerResponse();
    }

    /**
     * Create an instance of {@link DeleteCustomer }
     * 
     */
    public DeleteCustomer createDeleteCustomer() {
        return new DeleteCustomer();
    }

    /**
     * Create an instance of {@link GetAllCustomer }
     * 
     */
    public GetAllCustomer createGetAllCustomer() {
        return new GetAllCustomer();
    }

    /**
     * Create an instance of {@link UpdateCustomer }
     * 
     */
    public UpdateCustomer createUpdateCustomer() {
        return new UpdateCustomer();
    }

    /**
     * Create an instance of {@link AddCustomer }
     * 
     */
    public AddCustomer createAddCustomer() {
        return new AddCustomer();
    }

    /**
     * Create an instance of {@link GetCustomerResponse }
     * 
     */
    public GetCustomerResponse createGetCustomerResponse() {
        return new GetCustomerResponse();
    }

    /**
     * Create an instance of {@link DeleteCustomerResponse }
     * 
     */
    public DeleteCustomerResponse createDeleteCustomerResponse() {
        return new DeleteCustomerResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.ba.com/xsd", name = "city", scope = Customer.class)
    public JAXBElement<String> createCustomerCity(String value) {
        return new JAXBElement<String>(_CustomerCity_QNAME, String.class, Customer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.ba.com/xsd", name = "firstName", scope = Customer.class)
    public JAXBElement<String> createCustomerFirstName(String value) {
        return new JAXBElement<String>(_CustomerFirstName_QNAME, String.class, Customer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.ba.com/xsd", name = "lastName", scope = Customer.class)
    public JAXBElement<String> createCustomerLastName(String value) {
        return new JAXBElement<String>(_CustomerLastName_QNAME, String.class, Customer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.ba.com/xsd", name = "address", scope = Customer.class)
    public JAXBElement<String> createCustomerAddress(String value) {
        return new JAXBElement<String>(_CustomerAddress_QNAME, String.class, Customer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.ba.com/xsd", name = "phoneNumber", scope = Customer.class)
    public JAXBElement<String> createCustomerPhoneNumber(String value) {
        return new JAXBElement<String>(_CustomerPhoneNumber_QNAME, String.class, Customer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Customer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.ba.com", name = "customer", scope = GetCustomer.class)
    public JAXBElement<Customer> createGetCustomerCustomer(Customer value) {
        return new JAXBElement<Customer>(_GetCustomerCustomer_QNAME, Customer.class, GetCustomer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Customer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.ba.com", name = "customer", scope = UpdateCustomer.class)
    public JAXBElement<Customer> createUpdateCustomerCustomer(Customer value) {
        return new JAXBElement<Customer>(_GetCustomerCustomer_QNAME, Customer.class, UpdateCustomer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Customer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.ba.com", name = "customer", scope = AddCustomer.class)
    public JAXBElement<Customer> createAddCustomerCustomer(Customer value) {
        return new JAXBElement<Customer>(_GetCustomerCustomer_QNAME, Customer.class, AddCustomer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Customer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.ba.com", name = "return", scope = GetCustomerResponse.class)
    public JAXBElement<Customer> createGetCustomerResponseReturn(Customer value) {
        return new JAXBElement<Customer>(_GetCustomerResponseReturn_QNAME, Customer.class, GetCustomerResponse.class, value);
    }

}
