insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (1, 'Bran', 'Prahm', 'Manorom', '425 Bluestem Center', '(384) 2714415');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (2, 'Mitchael', 'Rymer', 'Sunchales', '9 7th Road', '(861) 5678168');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (3, 'Sutherland', 'Dallicott', 'Thanh Khê', '9 Northview Court', '(262) 2870547');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (4, 'Jobye', 'Dunstone', 'Qīrah', '1806 Hooker Junction', '(593) 2271294');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (5, 'Peri', 'Titherington', 'Camp Ithier', '85209 Bartillon Crossing', '(949) 4942517');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (6, 'Harriett', 'Andrzejczak', 'Salamanca', '92 Summit Parkway', '(648) 5848205');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (7, 'Robena', 'Kleynen', 'Chating', '807 Tomscot Place', '(267) 3029890');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (8, 'Lauri', 'Pigram', 'Cahuacho', '52555 Bluestem Road', '(205) 1435308');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (9, 'Fredi', 'Tutt', 'Drogomyśl', '1 1st Lane', '(328) 8000829');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (10, 'Romona', 'Franscioni', 'Rodhítsa', '74 Blue Bill Park Center', '(708) 6505341');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (11, 'Nikki', 'Oatley', 'Hobo', '42 American Crossing', '(794) 7808726');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (12, 'Ron', 'Neillans', 'Shabel’skoye', '059 Coleman Drive', '(503) 1394218');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (13, 'Patricio', 'Filer', 'Atolina', '2742 Sundown Center', '(857) 9185154');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (14, 'Alane', 'Doberer', 'Yamethin', '91 Badeau Parkway', '(110) 8753870');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (15, 'Nichole', 'Flegg', 'Xuling', '99 Hauk Center', '(769) 7749901');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (16, 'Robinet', 'Riglesford', 'Mtsensk', '662 Bultman Place', '(558) 9328966');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (17, 'Vincents', 'Trippack', 'Moravská Nová Ves', '5 Evergreen Street', '(878) 6992177');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (18, 'Edwina', 'Beningfield', 'Ludbreg', '24 Springs Crossing', '(152) 8293759');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (19, 'Dennet', 'Afield', 'Mechrá Belqsiri', '892 Maywood Pass', '(265) 2198526');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (20, 'Edee', 'Verbrugge', 'Villa Carlos Paz', '63 Cardinal Circle', '(243) 9784512');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (21, 'Barnie', 'Portigall', 'Kontiolahti', '7628 Warner Court', '(525) 3702611');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (22, 'Elsinore', 'Torra', 'Pawa', '3 Vahlen Parkway', '(457) 4701845');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (23, 'Xaviera', 'Froment', 'Calsib', '5941 Dakota Place', '(964) 5916892');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (24, 'Gearalt', 'Caulcutt', 'Mê Linh', '410 Anzinger Court', '(428) 1274278');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (25, 'Dieter', 'Jakab', 'Gapyeong', '4 Randy Trail', '(927) 5790563');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (26, 'Faye', 'Megarrell', 'Jardin', '0 Armistice Avenue', '(912) 8694520');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (27, 'Atlante', 'Farbrother', 'Pailitas', '44946 Lunder Park', '(463) 7634818');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (28, 'Marja', 'Corpes', 'Forshaga', '25 Northland Street', '(782) 7251206');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (29, 'Basilius', 'Veschambre', 'Mazha', '47 Eagan Street', '(628) 8410192');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (30, 'Sherline', 'O'' Liddy', 'Sanhui', '03 Kedzie Avenue', '(335) 4215230');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (31, 'Bettye', 'Artin', 'Timahankrajan', '274 Nelson Pass', '(720) 7126629');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (32, 'Bram', 'Monan', 'Carig', '96717 Holy Cross Road', '(594) 6738643');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (33, 'Gabi', 'Quin', 'Korolev', '83 Loeprich Junction', '(305) 9928035');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (34, 'Sadye', 'Waghorn', 'Garbów', '06262 Bashford Circle', '(730) 1338617');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (35, 'Gayel', 'Redpath', 'Dezhou', '740 Kenwood Road', '(760) 4646525');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (36, 'Roze', 'Dannel', 'Saitama', '88 Dottie Alley', '(580) 2111905');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (37, 'Geoffrey', 'Haylett', 'Pasirlimus', '79 Fordem Parkway', '(602) 7719899');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (38, 'Carry', 'Ovitts', 'Janeng', '90 Charing Cross Terrace', '(431) 5203106');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (39, 'Nolana', 'Dwelling', 'Wushi', '02 Rowland Place', '(313) 9173205');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (40, 'Anneliese', 'Petheridge', 'Rosais', '91112 Maywood Point', '(681) 7246012');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (41, 'Esme', 'Bonavia', 'Lepaterique', '14377 Donald Street', '(161) 4332280');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (42, 'Angeli', 'Olley', 'São Paio de Gramaços', '024 Old Gate Pass', '(428) 9059083');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (43, 'Kendell', 'Domoney', 'San Jacinto', '768 Memorial Center', '(862) 7249251');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (44, 'Corena', 'Vinau', 'Mysiadło', '474 Summit Lane', '(591) 6058887');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (45, 'Virgie', 'Bolitho', 'Dnipryany', '7156 Golden Leaf Park', '(710) 6212813');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (46, 'Kimmy', 'Eick', 'Looc', '98 Porter Road', '(675) 9627559');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (47, 'Solomon', 'Heinicke', 'Boromlya', '8 Golden Leaf Court', '(631) 6987980');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (48, 'Maurine', 'Witterick', 'Mapiri', '433 Dwight Hill', '(139) 5420145');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (49, 'Augustus', 'Gypps', 'Arīḩā', '65 Elka Parkway', '(468) 3569773');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (50, 'Constantine', 'Carlucci', 'Cubará', '6 Emmet Plaza', '(650) 5001817');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (51, 'Kimble', 'Fairhead', 'Huaidian', '61 Eagan Parkway', '(216) 5248625');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (52, 'Dicky', 'Miskimmon', 'Vila Franca da Beira', '32 Graceland Crossing', '(339) 7537478');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (53, 'Tarrah', 'Wheelband', 'Mujiangping', '5 Dwight Avenue', '(633) 5253255');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (54, 'Cody', 'Burkin', 'Damu', '67 Cardinal Court', '(818) 4578931');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (55, 'Davon', 'Merrikin', 'Miguel Hidalgo', '4 Sutteridge Pass', '(288) 4203072');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (56, 'Loraine', 'Eggins', 'Río Bueno', '40268 Maple Wood Point', '(104) 5274474');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (57, 'Ailbert', 'Groocock', 'Lewolere', '7 Northwestern Drive', '(907) 2596679');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (58, 'Maxi', 'Sibyllina', 'Dalaba', '5815 Vera Junction', '(753) 3706688');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (59, 'Renaldo', 'Jevons', 'Morrison', '2 Kinsman Center', '(111) 5453523');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (60, 'Lisetta', 'Walby', 'Opatovice nad Labem', '3 Corscot Park', '(276) 9949049');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (61, 'Moses', 'Raggitt', 'Vailoa', '3648 Burning Wood Center', '(779) 8030685');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (62, 'Welsh', 'Fusco', 'Magsaysay', '03 Stephen Pass', '(719) 8770984');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (63, 'Nonie', 'Cragg', 'Armen', '62 Garrison Terrace', '(816) 5650776');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (64, 'Vikki', 'Coneau', 'Cullalabo del Sur', '3212 Leroy Avenue', '(248) 7249518');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (65, 'Torey', 'Brinkworth', 'Lüfeng', '61 Logan Park', '(581) 6268507');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (66, 'Rosie', 'Leader', 'Ercheng', '876 Hagan Court', '(801) 4514440');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (67, 'Caro', 'Demer', 'Nhơn Trạch', '54042 Clove Road', '(365) 2307668');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (68, 'Ferrell', 'Stoad', 'Chirilagua', '7 1st Hill', '(352) 7600391');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (69, 'Dorri', 'Windley', 'Datong', '576 Raven Parkway', '(908) 5156663');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (70, 'Consalve', 'Myrkus', 'Mengzhai', '756 Londonderry Center', '(489) 1841182');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (71, 'Clemence', 'Amberger', 'Kantharalak', '9 Shoshone Way', '(742) 4373910');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (72, 'Chrisy', 'Haulkham', 'Xiaochi', '86302 Mariners Cove Pass', '(953) 9422431');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (73, 'Barthel', 'Broadbury', 'Chekhov', '2294 Barby Hill', '(449) 8345022');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (74, 'Harp', 'Headley', 'Stadtbredimus', '943 Rigney Way', '(452) 3520397');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (75, 'Ursola', 'Hammett', 'Kcynia', '0 Melody Way', '(334) 4850161');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (76, 'Cary', 'Isley', 'Chongxian', '8 Blue Bill Park Alley', '(281) 1120672');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (77, 'Rochell', 'Crowcum', 'Wu’an', '5 Oak Valley Circle', '(604) 7205859');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (78, 'Gilda', 'Sawbridge', 'Yokohama', '68 Dennis Parkway', '(563) 6019073');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (79, 'Gayler', 'Skerrett', 'Figueiras', '6 Dryden Way', '(988) 4386238');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (80, 'Corena', 'Probat', 'Sabinópolis', '2 Warbler Terrace', '(597) 4136972');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (81, 'Lazarus', 'Stagg', 'Pil’na', '9 Granby Place', '(728) 7788531');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (82, 'Rabbi', 'McVaugh', 'Blama', '98 Huxley Lane', '(100) 6372181');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (83, 'Francis', 'Goundsy', 'Opatów', '51422 Commercial Pass', '(735) 7166219');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (84, 'Giordano', 'Titherington', 'Kapchorwa', '4 Parkside Hill', '(291) 4063403');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (85, 'Hillary', 'Voase', 'Sulyukta', '2 Sugar Lane', '(726) 9488512');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (86, 'Nicole', 'Proby', 'Venezia', '4 Nevada Point', '(210) 3210404');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (87, 'Kristien', 'Ulyatt', 'Philadelphia', '549 Steensland Park', '(215) 9655540');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (88, 'Neddie', 'Whifen', 'Nankāna Sāhib', '4827 Dexter Lane', '(454) 8464932');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (89, 'Stanton', 'Langthorne', 'Hodkovičky', '3 Eastwood Lane', '(477) 8692321');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (90, 'Brannon', 'Herrema', 'Santa Rosa', '844 Stuart Terrace', '(707) 3951985');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (91, 'Rudie', 'Fosken', 'Leye', '196 Sloan Center', '(777) 6101568');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (92, 'Granville', 'Chad', 'Gornja Koprivna', '01 Bay Drive', '(899) 5728601');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (93, 'Emelyne', 'Shere', 'Río Cuarto', '93 Barby Street', '(926) 5096051');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (94, 'Damita', 'Pedroni', 'San Salvador', '15773 Prentice Street', '(551) 2122211');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (95, 'Jaclin', 'Carman', 'Sudislavl’', '2710 Huxley Park', '(605) 3013412');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (96, 'Talbot', 'Goodbar', 'Nizhniy Lomov', '3885 Sycamore Drive', '(448) 6841987');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (97, 'Bat', 'Sutton', 'Pa Bon', '273 Bayside Hill', '(645) 9774937');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (98, 'Polly', 'Appleyard', 'Paulba', '06578 Kensington Drive', '(612) 3468832');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (99, 'Malorie', 'Scorrer', 'Licheń Stary', '8 Westport Hill', '(545) 4518794');
insert into CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, CITY, ADDRESS, PHONENUMBER) values (100, 'Crawford', 'Matheson', 'Revolucion', '56190 Stuart Road', '(624) 2146676');
