insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (1, 'Flavouring Vanilla Artificial', 'Vol Au Vents', 28, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (2, 'Shrimp - 16/20, Peeled Deviened', 'Mikes Hard Lemonade', 39, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (3, 'Wine - Casillero Del Diablo', 'Beer - Pilsner Urquell', 48, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (4, 'Pepper Squash', 'Wine - Beaujolais Villages', 41, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (5, 'Magnotta Bel Paese Red', 'Bread - Assorted Rolls', 28, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (6, 'Containter - 3oz Microwave Rect.', 'Wine - Pinot Noir Latour', 7, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (7, 'Water - Spring 1.5lit', 'Melon - Watermelon Yellow', 23, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (8, 'Wine - Magnotta, White', 'Beef Tenderloin Aaa', 8, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (9, 'Pork - Bacon,back Peameal', 'Laundry - Bag Cloth', 18, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (10, 'Cheese - Havarti, Roasted Garlic', 'Shrimp - 16/20, Iqf, Shell On', 44, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (11, 'Tandoori Curry Paste', 'Duck - Fat', 22, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (12, 'Tofu - Firm', 'Soup - Cream Of Broccoli, Dry', 43, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (13, 'Icecream Cone - Areo Chocolate', 'Pork - Back Ribs', 22, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (14, 'Mix - Cocktail Strawberry Daiquiri', 'Cheese - Gouda Smoked', 23, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (15, 'Cookie Dough - Peanut Butter', 'Chocolate - Mi - Amere Semi', 40, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (16, 'Thermometer Digital', 'Flax Seed', 21, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (17, 'Asparagus - Green, Fresh', 'Fondant - Icing', 17, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (18, 'Cornstarch', 'Tia Maria', 8, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (19, 'Lettuce - Arugula', 'Chocolate - Milk, Callets', 1, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (20, 'Butcher Twine 4r', 'Cookies - Oreo, 4 Pack', 27, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (21, 'Bread - Pita', 'Mushroom - Morel Frozen', 10, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (22, 'Glucose', 'Kellogs Cereal In A Cup', 27, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (23, 'Cheese - Montery Jack', 'Pepper - Chillies, Crushed', 38, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (24, 'Grapes - Red', 'Cheese - Comte', 30, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (25, 'Rhubarb', 'Wine - Zinfandel Rosenblum', 5, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (26, 'Chutney Sauce - Mango', 'Soup - Campbells Beef Strogonoff', 40, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (27, 'Taro Leaves', 'Lettuce - Radicchio', 12, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (28, 'Wine - Taylors Reserve', 'Sesame Seed', 19, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (29, 'Trueblue - Blueberry 12x473ml', 'Bread - Frozen Basket Variety', 36, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (30, 'Bread Base - Italian', 'Compound - Raspberry', 38, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (31, 'Melon - Cantaloupe', 'Bread - Olive Dinner Roll', 29, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (32, 'Cup - Translucent 7 Oz Clear', 'Barramundi', 38, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (33, 'Cheese - Brick With Pepper', 'Chips Potato Swt Chilli Sour', 49, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (34, 'Turkey - Breast, Boneless Sk On', 'Rice Wine - Aji Mirin', 6, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (35, 'Sunflower Seed Raw', 'Flour - Bran, Red', 29, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (36, 'Roe - White Fish', 'Jolt Cola', 12, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (37, 'Maintenance Removal Charge', 'Wine - Muscadet Sur Lie', 2, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (38, 'Halibut - Whole, Fresh', 'Rice - Wild', 46, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (39, 'Eggs - Extra Large', 'Flower - Leather Leaf Fern', 41, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (40, 'Alize Red Passion', 'Truffle Cups Green', 23, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (41, 'Apple - Delicious, Red', 'Mangostein', 24, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (42, 'Wine - Balbach Riverside', 'Chicken Thigh - Bone Out', 12, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (43, 'V8 - Berry Blend', 'Lobak', 11, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (44, 'Lid - Translucent, 3.5 And 6 Oz', 'Cheese - Montery Jack', 35, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (45, 'Cheese - Wine', 'Beans - Kidney, Red Dry', 35, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (46, 'Sponge Cake Mix - Vanilla', 'Tray - Foam, Square 4 - S', 23, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (47, 'Beer - Corona', 'Spice - Greek 1 Step', 1, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (48, 'Ecolab - Balanced Fusion', 'Tomato - Plum With Basil', 23, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (49, 'Beef - Tongue, Fresh', 'Vodka - Smirnoff', 31, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (50, 'Tahini Paste', 'Squid - U 5', 48, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (51, 'Bar - Granola Trail Mix Fruit Nut', 'Vacuum Bags 12x16', 29, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (52, 'Red Cod Fillets - 225g', 'Lid - High Heat, Super Clear', 34, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (53, 'Cheese - Cottage Cheese', 'Spice - Chili Powder Mexican', 34, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (54, 'Flour - Bran, Red', 'Ecolab Crystal Fusion', 29, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (55, 'Venison - Ground', 'Soup - Campbells Chili Veg', 44, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (56, 'Vegetable - Base', 'Bread - White Epi Baguette', 13, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (57, 'Wine - Valpolicella Masi', 'Wine - Stoneliegh Sauvignon', 22, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (58, 'Pur Source', 'Cookies - Fortune', 20, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (59, 'Peach - Halves', 'Gatorade - Cool Blue Raspberry', 41, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (60, 'Chocolate - Unsweetened', 'Stock - Veal, White', 25, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (61, 'Otomegusa Dashi Konbu', 'Pork - Backfat', 15, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (62, 'Egg - Salad Premix', 'Oil - Safflower', 10, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (63, 'Nantucket - 518ml', 'Tart - Raisin And Pecan', 21, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (64, 'Rhubarb', 'Sage - Rubbed', 26, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (65, 'Wine - Piper Heidsieck Brut', 'Relish', 25, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (66, 'Lamb - Rack', 'Cookie Chocolate Chip With', 29, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (67, 'Sauce - Fish 25 Ozf Bottle', 'Wine - Magnotta - Cab Franc', 46, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (68, 'Juice - Mango', 'Flour - Cake', 22, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (69, 'Beef - Ox Tongue, Pickled', 'Bagels Poppyseed', 21, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (70, 'Bread Country Roll', 'Marzipan 50/50', 7, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (71, 'Onions - Vidalia', 'Beef - Top Butt Aaa', 36, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (72, 'Lamb - Ground', 'Beef - Short Ribs', 17, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (73, 'Sugar - Palm', 'General Purpose Trigger', 32, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (74, 'Grapes - Black', 'V8 Pet', 36, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (75, 'Veal - Eye Of Round', 'Water - Green Tea Refresher', 41, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (76, 'Cake - Sheet Strawberry', 'Pike - Frozen Fillet', 8, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (77, 'Pasta - Ravioli', 'Grapefruit - Pink', 20, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (78, 'Smoked Paprika', 'Ecolab - Power Fusion', 7, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (79, 'Table Cloth 81x81 Colour', 'Carbonated Water - Wildberry', 13, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (80, 'Wasabi Powder', 'Pepper - Black, Ground', 23, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (81, 'Sage Derby', 'Plaintain', 6, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (82, 'Figs', 'Lettuce - Romaine, Heart', 4, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (83, 'Yogurt - Strawberry, 175 Gr', 'Tart Shells - Sweet, 3', 22, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (84, 'Tomato Puree', 'Sauce - Vodka Blush', 3, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (85, 'Bar Special K', 'Cabbage - Nappa', 49, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (86, 'Fuji Apples', 'Turkey - Whole, Fresh', 13, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (87, 'Wine - White, Antinore Orvieto', 'Bread - Burger', 30, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (88, 'Tart - Butter Plain Squares', 'Pails With Lids', 49, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (89, 'Sauce Bbq Smokey', 'Juice - V8 Splash', 40, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (90, 'Pastry - Apple Muffins - Mini', 'Pasta - Fettuccine, Dry', 22, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (91, 'Wine - Sawmill Creek Autumn', 'Pernod', 21, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (92, 'Tofu - Soft', 'Wine - Chateau Timberlay', 15, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (93, 'Beef Dry Aged Tenderloin Aaa', 'Dooleys Toffee', 27, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (94, 'Beef - Ground Lean Fresh', 'Chinese Foods - Chicken', 47, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (95, 'Veal - Heart', 'Chestnuts - Whole,canned', 29, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (96, 'Nacho Chips', 'Salmon - Smoked, Sliced', 7, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (97, 'Sauce - White, Mix', 'Wine - Domaine Boyar Royal', 46, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (98, 'Clams - Bay', 'Cake - Night And Day Choclate', 12, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (99, 'Fish - Atlantic Salmon, Cold', 'Cheese - Fontina', 8, 1);
insert into PRODUCT (ID, TITLE, DESCRIPTION, PRICE, MEDIA_ID) values (100, 'Nantucket Pine Orangebanana', 'Wine - Rubyport', 35, 1);



--

insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (1, 3, 1);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (2, 1, 2);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (3, 3, 3);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (4, 2, 4);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (5, 1, 5);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (6, 3, 6);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (7, 2, 7);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (8, 2, 8);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (9, 3, 9);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (10, 3, 10);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (11, 1, 11);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (12, 2, 12);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (13, 2, 13);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (14, 1, 14);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (15, 3, 15);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (16, 2, 16);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (17, 1, 17);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (18, 1, 18);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (19, 2, 19);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (20, 3, 20);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (21, 2, 21);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (22, 1, 22);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (23, 3, 23);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (24, 2, 24);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (25, 3, 25);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (26, 1, 26);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (27, 1, 27);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (28, 3, 28);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (29, 3, 29);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (30, 3, 30);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (31, 3, 31);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (32, 3, 32);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (33, 3, 33);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (34, 1, 34);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (35, 2, 35);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (36, 3, 36);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (37, 1, 37);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (38, 3, 38);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (39, 1, 39);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (40, 1, 40);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (41, 2, 41);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (42, 2, 42);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (43, 3, 43);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (44, 3, 44);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (45, 3, 45);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (46, 2, 46);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (47, 1, 47);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (48, 1, 48);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (49, 1, 49);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (50, 3, 50);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (51, 1, 51);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (52, 1, 52);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (53, 3, 53);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (54, 2, 54);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (55, 1, 55);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (56, 1, 56);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (57, 1, 57);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (58, 1, 58);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (59, 1, 59);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (60, 1, 60);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (61, 1, 61);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (62, 1, 62);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (63, 1, 63);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (64, 3, 64);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (65, 2, 65);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (66, 1, 66);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (67, 3, 67);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (68, 2, 68);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (69, 2, 69);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (70, 2, 70);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (71, 1, 71);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (72, 1, 72);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (73, 1, 73);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (74, 2, 74);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (75, 3, 75);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (76, 3, 76);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (77, 2, 77);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (78, 1, 78);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (79, 1, 79);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (80, 3, 80);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (81, 1, 81);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (82, 2, 82);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (83, 2, 83);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (84, 2, 84);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (85, 1, 85);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (86, 2, 86);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (87, 1, 87);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (88, 1, 88);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (89, 1, 89);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (90, 1, 90);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (91, 3, 91);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (92, 2, 92);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (93, 1, 93);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (94, 2, 94);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (95, 1, 95);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (96, 1, 96);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (97, 3, 97);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (98, 3, 98);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (99, 2, 99);
insert into TBL_CATEGORY_PRODUCT (PRODUCT_ID, CATEGORY_ID, ID) values (100, 3, 100);
